
#logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG  

logging:
  level:
    org:
      springframework:
        web: INFO 
        transaction: INFO
        data: INFO
        security: INFO
      mybatis: DEBUG
    com:
      cntaiping: DEBUG  
      
security:
  basic:
    enabled: false
  user:
    name: tpcloud
    password: ENC@neBN4GAe6TjqETUTvbcFgw==

management:
  security:
    enabled: true

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
spring:
  http:
    encoding:
      charset: UTF-8
    multipart:
      location:
      max-file-size: 20MB
      max-request-size: 50MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterAccess=60s
  resources:
    #static-locations: file:/Maxos/svn/tpsvn/tpicxzc/src/trunk/tpcloud-ui-app/
    #static-locations: file:///E:/svn/tpsvn/tpicxzc/src/trunk/tpcloud-ui-app/
    static-locations: ${static.locations:file:/tpsys/app/webapps/webui}
  redis:
    database: 2
    host: 10.0.102.20
    port: 7001
    password: 123456
    timeout: 200
    pool:
      max-active: 3
      max-idle: 3
      max-wait: -1
      min-idle: 0

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 60000

rocketmq:
  nameServerAddress: 10.0.102.20:8876
  #secretKey: tphw123456
  #topicNamePrefix: ${spring.application.name}
  #evnTag: ${config.env:ip16}
  #maxReconsumeTime: 1
  

# app config
app:
  webui:
    excludedUrls: /,/**.html,/**.js,/utils/**,/dist/**,/sys/auth/**,/shutdown,/restart
    excludedUrlsAfterLogin: /pages/**,/sys/code/list/codetype
    sessionTimeout: 7200
    loginUrl: /sys/auth/signin
    logoutUrl: /sys/auth/signout
   

zuul:
  #sensitiveHeaders: Cookie,Set-Cookie,Authorization
  routes:
    sys:
      path: /sys/**
      serviceId: tpcloud-service-system-dev
      #url: http://127.0.0.1:8806
    bpm:
      path: /bpm/**
      serviceId: tpcloud-service-bpm-dev
      #url: http://127.0.0.1:8808
    schedule:
      path: /schedule/**
      serviceId: tpcloud-service-schedule-dev
      #url: http://127.0.0.1:8809
    activiti:
      path: /activiti/**
      serviceId: tpcloud-service-activiti-dev
      #url: http://127.0.0.1:8810
    credit:
      path: /credit/**
      serviceId: tpcloud-service-credit-dev
      #url: http://127.0.0.1:8810 